---
version: "2.1"
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${ROOT}/config/plex/db:/config
      - ${ROOT}/downloads:/downloads
      # - ${ROOT}/downloads:/downloads/movies
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT}/config/qbittorrent:/config
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/incomplete:/incomplete
    ports:
      - 8080:8080 # access the web ui via port 8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sabnzbd:/config
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/incomplete:/incomplete
    ports:
      - 8081:8080 # access the web ui via port 8081
    restart: unless-stopped
