---
version: "3.2"

secrets: # {{{
   duckdns_token:
     file: ./duckdns_token.secret # }}}

include: # {{{
  - monitoring/docker-compose.yml # }}}

services:

  duckdns: # {{{
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - SUBDOMAINS=novick
      - FILE__TOKEN=/run/secrets/duckdns_token
      # - TOKEN=5d30cb99-967d-4ab9-b9b1-fcaf7f9c5b5f
    volumes:
      - ${CONFIG_ROOT}/duckdns:/config
    restart: unless-stopped
    secrets:
      - duckdns_token # }}}

  nginx-proxy-manager: # {{{
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TP_THEME=${THEME}
    ports:
      - '80:80'   # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81'   # Admin Web Port
    volumes:
      - ${CONFIG_ROOT}/nginx/data:/data
      - ${CONFIG_ROOT}/nginx/letsencrypt:/etc/letsencrypt
      - ${CONFIG_ROOT}/nginx/98-themepark:/etc/cont-init.d/98-themepark
    restart: unless-stopped # }}}

  qbittorrentvpn: # {{{
    container_name: qbittorrentvpn
    image: ghcr.io/hotio/qbittorrent
    ports:
      - "8080:8080"
      - "8118:8118"
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK=002
      - VPN_ENABLED=true
      - VPN_LAN_NETWORK=192.168.29.0/24
      - VPN_CONF=wg0
      - VPN_ADDITIONAL_PORTS
      - PRIVOXY_ENABLED=false
    volumes:
      - ${CONFIG_ROOT}/qbittorrentvpn:/config
      - ${DATA_ROOT}/torrents:/data/torrents
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1 # }}}

  sabnzbd: # {{{
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sabnzbd
      - TP_THEME=${THEME}
    volumes:
      - ${CONFIG_ROOT}/sabnzbd:/config
      - ${DATA_ROOT}/usenet:/data/usenet
    ports:
      - "8081:8080" # web UI
    restart: unless-stopped # }}}

  plex: # {{{
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_THEME=${THEME}
    volumes:
      - ${CONFIG_ROOT}/plex:/config
      - ${DATA_ROOT}/media:/data/media
    restart: unless-stopped # }}}

  # jellyfin: # {{{
  #   image: lscr.io/linuxserver/jellyfin:latest
  #   container_name: jellyfin
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${CONFIG_ROOT}/jellyfin:/config
  #     - ${DATA_ROOT}/media:/data/media
  #   devices:
  #     - /dev/dri:/dev/dri
  #   ports:
  #     - 8096:8096     # HTTP web UI
  #     - 8920:8920     # HTTPS web UI (optional)
  #     - 7359:7359/udp # Jellyfin client discovery (optional)
  #     - 1900:1900/udp # DLNA client discovery (optional)
  #   restart: unless-stopped # }}}

  tautulli: # {{{
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:tautulli
      - TP_THEME=${THEME}
    volumes:
      - ${CONFIG_ROOT}/tautulli:/config
    ports:
      - 8181:8181
    restart: unless-stopped # }}}

  prowlarr: # {{{
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${THEME}
    volumes:
      - ${CONFIG_ROOT}/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped # }}}

  radarr: # {{{
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${THEME}
    volumes:
      - ${CONFIG_ROOT}/radarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "7878:7878"
    restart: unless-stopped # }}}

  sonarr: # {{{
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${THEME}
    volumes:
      - ${CONFIG_ROOT}/sonarr:/config
      - ${DATA_ROOT}:/data
    ports:
      - "8989:8989"
    restart: unless-stopped # }}}

  overseerr: # {{{
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/overseerr:/config
    ports:
      - "5055:5055"
    restart: unless-stopped # }}}

  bazarr: # {{{
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_ROOT}/bazarr:/config
      - ${DATA_ROOT}/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped # }}}
  
# vim:fdm=marker
