---
version: "2.1"
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${ROOT}/config/plex/db:/config
      - ${ROOT}/downloads:/downloads
      # - ${ROOT}/downloads:/downloads/movies
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - ${ROOT}/config/qbittorrent:/config
      - ${ROOT}/downloads:/downloads
    ports:
      - 8080:8080 # access the web ui via port 8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ${ROOT}/sabnzbd:/config
      - ${ROOT}/downloads:/downloads #optional
      - ${ROOT}:/incomplete-downloads #optional
    ports:
      - 8081:8080 # access the web ui via port 8081
    restart: unless-stopped
