---
version: "2.1"
services:

  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/wireguard:/config
    ports:
      - "8080:8080" # qBittorrent WebUI
      - "6881:6881"
      - "6881:6881/udp"
      - "51820:51820/udp"
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:wireguard
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - WEBUI_PORT=8080
      - DOCKER_MODS=ghcr.io/gabe565/linuxserver-mod-vuetorrent
    volumes:
      - ${ROOT}/config/qbittorrent:/config
      - ${ROOT}/data/torrents:/data/torrents
    restart: unless-stopped

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:plex
      - TP_THEME=${THEME}
    volumes:
      - ${ROOT}/config/plex:/config
      - ${ROOT}/data/media:/media
      # - /mnt/elements:/elements # network share
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:prowlarr
      - TP_THEME=${THEME}
    volumes:
      - ${ROOT}/config/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=${THEME}
    volumes:
      - ${ROOT}/config/radarr:/config
      - ${ROOT}/data:/data
    ports:
      - "7878:7878"
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=${THEME}
    volumes:
      - ${ROOT}/config/sonarr:/config
      - ${ROOT}/data:/data
    ports:
      - "8989:8989"
    restart: unless-stopped

  # overseerr:
  #   image: lscr.io/linuxserver/overseerr:latest
  #   container_name: overseerr
  #   network_mode: host
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #   volumes:
  #     - ${ROOT}/config/overseer:/config
  #   restart: unless-stopped

  # bazarr:
  #   image: lscr.io/linuxserver/bazarr:latest
  #   container_name: bazarr
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - DOCKER_MODS=ghcr.io/gilbn/theme.park:bazarr
  #     - TP_THEME=${THEME}
  #   volumes:
  #     - ${ROOT}/config/bazarr:/config
  #     - ${ROOT}/data/media:/data/media
  #   ports:
  #     - 6767:6767
  #   restart: unless-stopped

  # sabnzbd:
  #   image: lscr.io/linuxserver/sabnzbd:latest
  #   container_name: sabnzbd
  #   environment:
  #     - PUID=${PUID}
  #     - PGID=${PGID}
  #     - TZ=${TZ}
  #     - DOCKER_MODS=ghcr.io/gilbn/theme.park:sabnzbd
  #     - TP_THEME=${THEME}
  #   volumes:
  #     - ${ROOT}/config/sabnzbd:/config
  #     - ${ROOT}/data/usenet:/data/usenet
  #   ports:
  #     - "8081:8080" # web UI
  #   restart: unless-stopped

