---
version: "2.1"
services:

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - ${ROOT}/config/plex:/config
      - ${ROOT}/downloads:/downloads # qBitTorrent/SABnzbd completed downloads
      - /mnt/elements:/elements # network share
    restart: unless-stopped

  qbittorrentvpn:
    image: dyonr/qbittorrentvpn
    container_name: qbittorrentvpn
    privileged: true
    volumes:
      - ${ROOT}/config:/config
      - ${ROOT}/downloads:/downloads
      - ${ROOT}/incomplete:/incomplete
    environment:
      - VPN_ENABLED=yes
      - VPN_TYPE=wireguard
      - LAN_NETWORK=192.168.29.0/24
      - PUID=1000
      - PGID=1000
      - INSTALL_PYTHON3=yes
    ports:
      - 8080:8080 # web UI
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - ${ROOT}/config/sabnzbd:/config
      - ${ROOT}/downloads:/config/Downloads/complete
      - ${ROOT}/incomplete:/config/Downloads/incomplete
    ports:
      - 8081:8080 # web UI
    restart: unless-stopped

